src/structures/Tweet.js
This PR adds the new `Tweet` structure that represents a tweet on Twitter. A lot of properties of this structure are yet to be implemented.
=> feat: add Tweet structure

src/util/Constants.js, src/util/StructureBuilder.js
Twitter recently released a new tweet field named `reply_settings` which states who can reply to a given tweet. This PR adds that field to `tweetFields` while also adding the `pinnedTweet` property of a `User` object.
=> feat: add reply_settings to tweetFields and pinnedTweet property to User

src/structures/Entity.js, src/structures/User.js, src/util/ResponseCleaner.js, src/util/StructureBuilder.js
This PR adds a new `Entity` structure. This structure can be accessed from the `entities` property of a `User` object. The PR also fixes some bugs like error related to `pinnedTweet` when fetching a `User` that has no pinned tweet.
=> feat: add a new Entity structure and a few bug fixes

src/client/Client.js, src/managers/TweetManager.js, src/util/Constants.js
This PR adds a new manager for `Tweet` objects. The manager can be accessed through the `tweets` property of `Client` object. It also removes three media fields from the tweet endpoint as they need user auth.
=> feat: add TweetManager and remove media fields that need user auth

src/structures/Media.js
This PR adds a new structure that represents media like image, video, or gif in a tweet. This structure isn't complete yet. I'll add more to it later.
=> feat(Media): add new structure for media in a tweet

src/structures/Place.js
This PR adds a new structure that represents a place tagged in a tweet. The `geo` property of this structure is yet to be implemented.
=> feat(Place): add new structure for place tagged in a tweet

src/structures/Attachment.js, src/util/StructureBuilder.js
This PR adds a new structure that holds all the attachments like media and polls present in a tweet.
=> feat(Attachment): add new structure for attachments in a tweet

src/structures/Tweet.js, src/structures/TweetPublicMetrics.js
This PR adds a new `TweetPublicMetrics` structure that represents public metrics of a tweet eg. `like`, `retweet` etc. It also implements the `publicMetrics` property of `Tweet`.
=> feat: add strucutre and property for tweet public metrics

src/structures/User.js, src/util/StructureBuilder.js
This PR moves some code that builds the `publicMetrics` and `entities` property of a user object from `StructureBuilder` to `User` class.
=> refactor(User): move some code from StructureBuilder to User

src/structures/BaseEntity.js, src/structures/Tweet.js, src/structures/TweetEntity.js, src/structures/User.js, src/structures/UserEntity.js
This PR adds `BaseEntity`, a base class for all entity classes. It also adds two new classes `UserEntity` and `TweetEntity` that will hold the entities for `User` and `Tweet` respectively. The old `Entity` class will be removed soon.
=> feat: add base class for entity classes

src/structures/BaseEntity.js, src/structures/User.js, src/util/ResponseCleaner.js, src/util/StructureBuilder.js
This PR removes the redundant code that sets the data for `publicMetrics` and `entities` property of author `(User)` object in `StructureBuilder#_patchTweet` since those functionalities were moved into the `User` class itself in PR: #23. It also fixes the name of `BaseEntity` class and a jsdoc tag for the `User#entities`.
=> fix: remove redundant code and fix some jsdoc tags

src/structures/AttachmentKey.js, src/structures/Tweet.js
This PR adds a new `AttachmentKey` structure that holds keys and ids of all attachments present in a tweet. The mentioned structure can be accessed through the new `attachmentKeys` property of `Tweet`.
=> feat: add structure for keys of attachments in tweet

src/structures/ContextAnnotation.js, src/structures/Tweet.js
This PR adds a new `ContextAnnotation` structure that represents a context annotation parsed by Twitter from the text of a tweet. The structure can be accessed through `Tweet#contextAnnotaions`.
=> feat: add structure for context annotations

src/client/Client.js, src/rest/RESTManager.js, test/test.js, typings/index.d.ts
This PR makes the `token` property of `Client` an object. From now on the token will hold all the bot credentials and not just the bearer token. The bearer token will still be used where it can be used. Other credentials will be used only for the endpoints that support `OAuth 1.0 user context` only.
=> feat(token): make token an object that holds bot credentials

src/managers/BaseManager.js, src/managers/TweetManager.js, src/managers/UserManager.js, src/rest/EndpointResolver.js, src/rest/RESTManager.js, src/structures/Tweet.js, src/structures/User.js, typings/index.d.ts
I started with `string` for the ID type but then I read about `Snowflake` and changed it. That was a mistake, so from now on all the IDs will have `string` type to keep it consistent with the API.
=> refactor: replace Snowflake with string type

package-lock.json, package.json, src/rest/EndpointResolver.js, src/rest/HeaderResolver.js, src/rest/RESTManager.js, src/structures/Tweet.js, src/util/Constants.js
This PR adds two new methods to the `Tweet` structure. `Tweet#hideReply` hides a reply to the tweet and `Tweet#unhideReply` unhides a reply to the tweet. The PR also adds a new dependency for making user-context API calls like these two methods. I might make a module of my own for this later but till then we are going to use `oauth-1.0a` package.
=> feat(Tweet): add hideReply and unhideReply methods

src/rest/EndpointResolver.js, src/rest/RESTManager.js, src/structures/AttachmentKey.js, src/structures/Tweet.js
This PR adds some new changes that are either to keep consistency with the API for property names of structures or for the internal naming convention of function names.
=> fix: some changes for keeping consistency

src/rest/EndpointResolver.js, src/rest/RESTManager.js, src/structures/User.js, src/util/ResponseCleaner.js
This PR adds a new method to the `User` structure that fetches the users followed by the `User`. The underlying raw API caller `<RESTManager>#fetchUserFollowing` for this method is still incomplete. The `max_results` and `pagination` functionality is yet to be implemented on it.
=> feat(User): add method for fetching user following

src/structures/Meta.js, src/structures/PaginatedResponse.js, src/structures/User.js, test/test.js
Made the `follows-lookup` endpoint calls to use the new rest module. The paginated feature is now exposed to the end-user, which means the lib won't make looping requests to the endpoints that send a paginated response. Only one request will be made and if the user wants to get more pages, they can use the `meta` information sent in the current response.
=> feat: add paginated feature to follows-lookup endpoints

src/managers/TweetManager.js, src/structures/Tweet.js
This PR moves the hide-unhide reply methods on the `Tweet` to the `TweetManager`. From now on, the methods of the same name on `Tweet` will hide the tweet itself if it is a reply to a tweet made by the user.
=> feat(TweetManager): add hide-unhide reply methods

README.md
New endpoints were released today. One of them is covered, other is still left 🤒
=> chore: update api coverage list

src/managers/UserManager.js, src/structures/MiscResponses.js, src/structures/User.js
This PR adds `block` and `unblock` methods on both `User` and `UserManager` classes in order to provide support for the latest released `Manage Blocks` endpoints.
=> feat: add methods for blocking and unblocking a user

.vscode/settings.json, package-lock.json, package.json, src/client/Client.ts, src/errors/ErrorMessages.ts, src/managers/ListManager.ts, src/managers/index.ts, src/structures/List.ts, src/structures/index.ts, src/typings/Interfaces.ts, src/typings/Types.ts, src/util/Collection.ts
Adds support for: https://developer.twitter.com/en/docs/twitter-api/lists/manage-lists/api-reference
TODO:
=> feat: add support for manage lists endpoints and a list manager class

package-lock.json, package.json, src/client/Client.ts, src/structures/FilteredTweetStreamRule.ts, src/typings/Interfaces.ts
Adds a collection of matched rules as a second parameter to the `filteredTweetCreate` event. This will help in deciding which rule(s) got matched against the given filtered tweet.
=> feat: emit matching rules collection in filteredTweetCreate event
