twitterjs/twitter.js

typings/index.d.ts
Typings for the Tweet structure are not present in this PR. They will be implemented when I'll add more to that structure. Also, seems like the typings file was left out from the recent indentation rule changes. 😅
=> feat: update typings

.eslintrc.json, jsdoc.json, package-lock.json, package.json
Found some more files that were left out from the new indentation rules. This PR fixes that.
=> chore: fix the indentation

package.json, src/structures/User.js
This PR also fixes the jsdoc tags for two User properties.
=> chore: version upgrade

src/structures/UserPublicMetrics.js, src/util/StructureBuilder.js
This PR adds `publicMetrics` property to the `User` object. This property is implemented through a new `UserPublicMetrics` structure.
=> feat(User): add publicMetrics property and UserPublicMetrics strucutre

src/structures/Cashtag.js, src/structures/Hashtag.js
This PR adds two new `Hashtag` and `Cashtag` entities structure. I feel all of these entity structures should have a base class but I'll look into that later.
=> feat: add two more entity structures

src/structures/Hashtag.js, src/structures/Mention.js
=> fix: Mention username property and typo in Hashtag

src/errors/ErrorMessages.js, src/managers/TweetManager.js, src/util/ResponseCleaner.js, src/util/StructureBuilder.js
This PR adds more functionality to `TweetManager#fetch` as well as adds new utility methods related to it. There is a new `ErrorMessage` for invalid tweet IDs too.
=> feat(TweetManager): add more to fetch

src/managers/UserManager.js, src/util/StructureBuilder.js
This PR refactors some parts of `StructureBuilder` and changes a few variable names in `UserManager` for consistency purpose.
=> refactor: some cleaning of code

src/structures/Tweet.js, src/structures/User.js, typings/index.d.ts
1. This PR adds typings for the `Tweet` structure.
2. Updates typings of a few `User` properties.
3. Fixes a few jsdoc tag mistakes.
4. This PR also removes the `declare module` from the typings file.
=> feat: add typings for Tweet and fix some docs issues

src/structures/Poll.js
This PR adds a new structure that represents a poll in a tweet. The `options` property needs some more work, I'll come back to that later.
=> feat(Poll): add new structure for poll in a tweet

src/structures/Poll.js, src/structures/PollOption.js
This PR adds a new `PollOption` structure that represents an option in a `Poll` object.
=> feat: add new structure for poll options

package.json
=> chore: upgrade version

package.json, src/rest/EndpointResolver.js, src/rest/RESTManager.js, src/structures/User.js, test/test.js
This PR adds pagination to `RESTManager#fetchUserFollowing`, thus making it possible for `User#fetchFollowing` to return a complete collection of all the users followed by the `User`.
=> feat(RESTManager): add pagination to #fetchUserFollowing

src/rest/EndpointResolver.js, src/rest/RESTManager.js, src/structures/User.js
This PR adds `User#fetchFollowers`. It returns a collection of all users that are following the `User`.
=> feat(User): add #fetchFollowers

README.md, package.json
This PR adds a task list for API coverage in the README and updates the lib description. Also, it's v0.0.8 now 🚀
=> chore: add task list for API coverage

package.json
=> chore: version upgrade to v0.0.9

src/client/Client.js, src/managers/UserManager.js, src/structures/GeneralResponses.js, src/structures/Tweet.js, src/structures/User.js, test/test.js, typings/index.d.ts
This PR adds the `follow` method on `UserManager` and `User`.
=> feat: add method for following users

src/managers/UserManager.js, src/rest/APIRequest.js, src/structures/GeneralResponses.js, src/structures/User.js, test/test.js
This PR adds `UserManager#unfollow` and `User#unfollow` methods that can be used to unfollow a user on Twitter.
=> feat: add method to unfollow a user

src/errors/ErrorMessages.js, src/managers/TweetManager.js, src/managers/UserManager.js, src/structures/MiscResponses.js, src/util/StructureBuilder.js
=> chore: make some cosmetic changes

src/managers/TweetManager.js, typings/index.d.ts
This PR also fixes some typos in the jsdoc description.
=> feat(typings): add types for TweetManager and UserManager

typings/index.d.ts
Update typings for `User` class.
=> feat(typings): add typings for follow and unfollow methods of User

src/managers/TweetManager.js, src/structures/Tweet.js
This PR adds coverage for the [Manage Likes](https://developer.twitter.com/en/docs/twitter-api/tweets/likes/api-reference) endpoints.
=> feat: add support for (un)liking a tweet

.eslintrc.json, .github/workflows/lint.yml, .lintstagedrc.json, .prettierignore, .vscode/settings.json, package.json, src/rest/TwitterAPIError.ts, tsconfig.json, typedoc.json
=> chore: add npm scripts and github workflow for linting

package-lock.json, package.json, src/client/Client.ts, src/managers/__tests__/BaseManager.test.ts, src/rest/RequestHandler.ts, src/structures/BaseStructure.ts, src/structures/FilteredTweetStreamRule.ts, src/structures/Media.ts, src/structures/Place.ts, src/structures/Poll.ts, src/structures/SimplifiedSpace.ts, src/structures/SimplifiedTweet.ts, src/structures/SimplifiedUser.ts, src/typings/Interfaces.ts, src/util/Constants.ts
Also adds some tests for `BaseManager`
=> feat: add keepAliveSignal event & mv id field to BaseStructure

package-lock.json, package.json, src/managers/TweetManager.ts, src/structures/Tweet.ts, src/structures/TweetPayload.ts, src/structures/index.ts, src/typings/Interfaces.ts, src/typings/Types.ts
=> feat: add support for manage tweet endpoints

CONTRIBUTING.md
=> adding contribution guide
